"""
全域可配置字段中文目录（运营必读）。

对 effective/YAML 做路径展开，匹配本表得到 ``label_zh`` / ``help_zh``；
未登记路径仍列出并标「待补中文说明」，保证运营能看见**全部**可配置项。
"""

from __future__ import annotations

from typing import Any

# path 模式：`.` 分层；`*` 匹配单段键（不含点）
# 例：species.*.base_atk 、regions.*.pool.*
_PATH_HELP: dict[str, tuple[str, str]] = {
    # ---- pets ----
    "hold_cap": ("持有上限", "同时可持有灵宠数量上限"),
    "level_stat_bonus": ("每级属性加成", "相对基础面板的每级加成比例"),
    "races": ("种族表", "race_id → 种族定义"),
    "races.*": ("种族条目", "单个种族"),
    "races.*.name": ("种族名", "玩家可见"),
    "races.*.racial_talent_id": ("种族天赋 ID", "必带；须存在于 pet_passives"),
    "races.*.base_capture_rate": ("基础捕获率", "野外捕获底；0～1"),
    "grades": ("品阶表", "个体品阶 → 槽位与乘区"),
    "grades.*": ("品阶条目", "单个品阶"),
    "grades.*.name": ("品阶名", "如凡品/灵品"),
    "grades.*.affix_slots": ("词条槽上限", "最高 9"),
    "grades.*.type_reroll_slots": ("可改类型槽数", "灵兽宗 1～4"),
    "grades.*.base_mult": ("基础属性乘区", "相对品阶 1"),
    "capture_test_weights": ("测试捕获稀有度权重", "rarity → 权重"),
    "capture_test_weights.*": ("某稀有度权重", "整数"),
    "capture_test_grade_weights": ("测试捕获品阶权重", "grade → 权重"),
    "capture_test_grade_weights.*": ("某品阶权重", "整数"),
    "grade_up": ("升阶费用", "spirit_stones_base / grow / max_grade"),
    "grade_up.spirit_stones_base": ("升阶基础灵石", "升到品阶 2 的费用"),
    "grade_up.grow": ("升阶费用递增", "cost = base*(1+grow)^(target-2)"),
    "grade_up.max_grade": ("升阶上限", "不得超过 grades 最大键"),
    "sect_reroll": ("灵兽宗改类型费用", "PET-D06；enabled/base_1/grow"),
    "sect_reroll.enabled": ("费用表启用标记", "玩法闸仍读 sects 设施"),
    "sect_reroll.base_1": ("改类型基础价", "第 1 槽首次费用"),
    "sect_reroll.grow": ("同槽递增系数", "如 0.1"),
    "sect_reroll.note": ("费用备注", "运营说明"),
    "species": ("物种表", "灵宠物种 id → 定义"),
    "species.*": ("物种条目", "单个物种完整定义"),
    "species.*.name": ("展示名", "玩家可见物种名"),
    "species.*.race": ("种族 ID", "须存在于 races"),
    "species.*.rarity": ("稀有度", "common/rare/epic/legendary"),
    "species.*.roles": ("定位列表", "dps/tank/control/support"),
    "species.*.acquire_tags": ("获取途径白名单", "capture_test/gm_grant 等"),
    "species.*.skill_pool_id": ("技能池 ID", "对战技能；PET-D02"),
    "species.*.passive_pool_id": ("被动池 ID", "独立被动；PET-D03；可空"),
    "species.*.base_atk": ("基础攻击", "1 品阶基础攻击"),
    "species.*.base_hp": ("基础生命", "1 品阶基础生命"),
    "species.*.base_speed": ("基础速度", "比速/先攻相关"),
    "species.*.growth": ("成长系数", "升级成长；品阶不改成长"),
    "species.*.growth.atk": ("攻击成长", "系数"),
    "species.*.growth.hp": ("生命成长", "系数"),
    "species.*.growth.speed": ("速度成长", "系数"),
    "species.*.upgrade_cost": ("升级消耗", "灵石与材料列表"),
    "species.*.upgrade_cost.spirit_stones": ("升级灵石", "升级所需灵石数"),
    "species.*.upgrade_cost.materials": ("升级材料", "材料列表 item_id+quantity"),
    "species.*.upgrade_cost.materials.*.item_id": ("材料物品 ID", "须存在于道具表"),
    "species.*.upgrade_cost.materials.*.quantity": ("材料数量", "整数"),
    "species.*.divine_sense_cost": ("神识占用覆盖", "空则用默认宠占用"),
    # ---- divine_sense ----
    "base_capacity": ("基础神识容量", "整数"),
    "per_realm_bonus": ("境界容量加成", "major→加成"),
    "per_realm_bonus.*": ("某境界加成", "整数"),
    "costs": ("单位占用", "avatar/pet"),
    "costs.avatar": ("化身占用", "点数"),
    "costs.pet": ("灵宠默认占用", "点数"),
    # ---- avatar ----
    "unlock_major_realm": ("凝练门槛大境界", "如 jindan"),
    "max_avatars": ("化身上限", "定案必须为 1"),
    "initial_stat_ratio": ("初始属性比例", "凝练时相对本体"),
    "material_mod_placeholder": ("材料修正占位", "乘区"),
    "condense_spirit_stone_cost": ("凝练灵石", "整数"),
    "spirit_stone_cost_per_tick_ratio": ("化身耗石比例", "相对本体同境"),
    "feature_unlocks": ("功能解锁表", "feature_id→min_major/label/summary"),
    "feature_unlocks.*": ("功能条目", "单一功能解锁"),
    "feature_unlocks.*.min_major": ("最低大境界", "须在 realms"),
    "feature_unlocks.*.label_zh": ("功能中文名", "玩家可见"),
    "feature_unlocks.*.summary": ("功能说明", "玩家可见"),
    "transfer": ("互传规则", "allow/deny/retention"),
    "transfer.allow": ("允许互传资源", "列表"),
    "transfer.deny": ("拒绝互传资源", "列表"),
    "transfer.retention_ratio": ("保留率", "(0,1]"),
    "transfer.retention_by_major": ("境界覆盖保留率", "major→ratio"),
    "transfer.retention_by_major.*": ("某境界保留率", "(0,1]"),
    "transfer.min_amount": ("最小互传", "整数"),
    "transfer.summary": ("互传说明", "玩家可见"),
    "stamina": ("化身体力", "元婴起生效"),
    "stamina.base_cap": ("基础体力上限", "整数"),
    "stamina.cap_by_major": ("境界体力上限", "major→cap"),
    "stamina.cap_by_major.*": ("某境界体力上限", "整数"),
    "stamina.daily_action_cap": ("日行动上限", "整数"),
    "stamina.recovery": ("恢复规则", "per_hour/summary"),
    "stamina.recovery.per_hour": ("每小时恢复", "点数"),
    "stamina.recovery.summary": ("恢复说明", "玩家可见"),
    "stamina.action_costs": ("行动耗体表", "action→cost"),
    "stamina.action_costs.*": ("某行动耗体", "整数"),
    "stamina.allow_stamina_transfer": ("允许互传体力", "bool"),
    "idle": ("化身挂机速率", "三向"),
    "idle.spirit": ("修灵向", "cultivation_per_tick"),
    "idle.spirit.cultivation_per_tick": ("修灵每 tick", "整数"),
    "idle.body": ("炼体向", "enabled + 产出"),
    "idle.body.enabled": ("炼体速率启用", "bool"),
    "idle.body.body_tempering_per_tick": ("炼体每 tick", "整数"),
    "idle.crafting": ("制造向", "crafting_exp_per_tick"),
    "idle.crafting.crafting_exp_per_tick": ("制造每 tick", "整数"),
    "soft_ratio": ("软上限比例", "soft_cap=capacity×ratio"),
    "hard_ratio": ("硬上限比例", "hard_cap=capacity×ratio"),
    "overload_stat_mult": ("旧线性乘区", "无 bands 时兼容"),
    "backlash_idle_mult": ("旧反噬挂机乘区", "无表命中时兼容"),
    "overload_bands": ("超载阶梯", "按 load/capacity"),
    "overload_bands.*.max_load_ratio": ("档上限比值", "null=兜底"),
    "overload_bands.*.combat_stat_mult": ("战斗属性乘区", "0～1"),
    "overload_bands.*.zone": ("区域标签", "comfort/overload/critical"),
    "backlash_table": ("反噬表", "when→效果"),
    "backlash_table.*.when": ("触发条件", "如 over_hard"),
    "backlash_table.*.idle_mult": ("挂机乘区", "化身速率"),
    "backlash_table.*.set_flag": ("写角色反噬标记", "bool"),
    "backlash_table.*.summary": ("摘要", "玩家可见"),
    "species.*.evolve_to": ("进化目标", "物种 id；深挖"),
    # ---- pet_affixes（与体质分表）----
    "tier_weights": ("词条品级权重", "common/rare/epic/legendary → 权重"),
    "tier_weights.*": ("某品级权重", "整数"),
    "type_weights": ("词条类型抽取权重", "affix_type_id → 权重"),
    "type_weights.*": ("某类型权重", "整数；0 表示不进抽池"),
    "value_reroll": ("数值洗炼费用", "spirit_stones_base / grow"),
    "value_reroll.spirit_stones_base": ("洗炼基础灵石", "该槽首次费用"),
    "value_reroll.grow": ("洗炼递增系数", "cost = base*(1+grow)^(k-1)"),
    "types": ("词条类型表", "affix_type_id → 定义"),
    "types.*": ("词条类型条目", "单个类型"),
    "types.*.name": ("类型展示名", "玩家可见"),
    "types.*.kind": ("效果种类", "flat_atk/pct_hp/passive_ref 等"),
    "types.*.passive_id": ("被动引用", "kind=passive_ref 时必填"),
    "types.*.tier_ranges": ("品级数值区间", "tier → {min,max}"),
    "types.*.tier_ranges.*": ("某品级区间", "min/max"),
    "types.*.tier_ranges.*.min": ("区间下限", "含"),
    "types.*.tier_ranges.*.max": ("区间上限", "含"),
    # ---- pet_skills ----
    "equip_slots": ("装备栏位数", "最多 4"),
    "skills": ("技能表", "skill_id → 定义"),
    "skills.*": ("技能条目", "单个主动技能"),
    "skills.*.name": ("技能名", "玩家可见"),
    "skills.*.power": ("威力", "状态技可为 0"),
    "skills.*.accuracy": ("命中", "0～100"),
    "skills.*.category": ("类别", "physical/special/status"),
    "skills.*.priority": ("先制档", "整数"),
    "skills.*.pp": ("PP", "使用次数占位"),
    "skills.*.mutex_tags": ("互斥标签", "列表"),
    "pools": ("技能池表", "pool_id → 池"),
    "pools.*": ("技能池条目", "单个池"),
    "pools.*.name": ("池名称", "运营可见"),
    "pools.*.skill_ids": ("可学技能列表", "须落在 skills"),
    "pools.*.default_learned": ("捕获默认已学", "技能 id 列表"),
    "pools.*.default_equipped": ("捕获默认装备", "最多 equip_slots"),
    # ---- pet_skill_books ----
    "books": ("技能书表", "book_id → 定义"),
    "books.*": ("技能书条目", "单本"),
    "books.*.name": ("书名", "玩家可见"),
    "books.*.skill_id": ("解锁技能", "须存在于 skills"),
    "books.*.scope": ("适用范围", "universal/race/species"),
    "books.*.race_id": ("种族限定", "scope=race"),
    "books.*.species_id": ("物种限定", "scope=species"),
    # ---- pet_duel ----
    "max_rounds": ("最大回合", "超时按剩余 HP 判胜"),
    "damage_divisor": ("伤害分母", "atk*power/divisor"),
    "damage_roll_min": ("伤害随机下限", "如 0.85"),
    "damage_roll_max": ("伤害随机上限", "如 1.0"),
    "accuracy_enabled": ("启用命中", "bool"),
    "speed_tie_break": ("同速决胜", "seed_parity"),
    "default_struggle": ("默认挣扎", "无技能时指令"),
    "default_struggle.skill_id": ("挣扎技能 ID", "字符串"),
    "default_struggle.name": ("挣扎名", "展示"),
    "default_struggle.power": ("挣扎威力", "整数"),
    "default_struggle.accuracy": ("挣扎命中", "整数"),
    "default_struggle.category": ("挣扎类别", "physical/special/status"),
    "default_struggle.priority": ("挣扎先制", "整数"),
    "default_struggle.pp": ("挣扎 PP", "整数"),
    "npc_templates": ("NPC 模板表", "npc_id → 定义"),
    "npc_templates.*": ("NPC 条目", "单个模板"),
    "npc_templates.*.name": ("NPC 名", "展示"),
    "npc_templates.*.species_id": ("物种 ID", "须存在于 pets"),
    "npc_templates.*.grade": ("品阶", "整数"),
    "npc_templates.*.level": ("等级", "整数"),
    "npc_templates.*.skill_ids": ("技能列表", "须存在于 pet_skills"),
    # ---- pet_eggs ----
    "max_concurrent": ("并发孵化上限", "0=不限"),
    "eggs": ("蛋表", "egg_id → 定义"),
    "eggs.*": ("蛋条目", "单个蛋"),
    "eggs.*.name": ("蛋名", "展示"),
    "eggs.*.species_id": ("物种 ID", "须含 egg_hatch"),
    "eggs.*.hatch_seconds": ("孵化秒数", "0=立刻可领"),
    "eggs.*.spirit_stones": ("开工灵石", "额外费用"),
    "eggs.*.grade_weights": ("品阶权重", "grade→权重"),
    "eggs.*.grade_weights.*": ("某品阶权重", "整数"),
    # ---- pet_passives ----
    "passives": ("被动表", "passive_id → 定义"),
    "passives.*": ("被动条目", "天赋或独立被动"),
    "passives.*.name": ("被动名", "展示"),
    "passives.*.kind": ("种类", "racial_talent/independent"),
    "passives.*.effect_domain": ("效果域", "combat/life/cultivation"),
    "passives.*.effects": ("数值效果", "flat_atk/pct_hp 等"),
    "passives.*.effects.*": ("单项效果值", "数值"),
    "passives.*.summary": ("摘要", "说明"),
    "pools": ("被动池表", "pool_id → 权重"),
    "pools.*": ("被动池条目", "单个池"),
    "pools.*.empty_weight": ("空抽权重", "可抽到无被动"),
    "pools.*.weights": ("被动权重", "passive_id→权重"),
    "pools.*.weights.*": ("某被动权重", "整数"),
    # ---- pet_feed ----
    "total_feed_cap": ("默认喂养总量上限", "0=不限"),
    "total_feed_cap_by_grade": ("品阶总量上限", "grade→上限"),
    "total_feed_cap_by_grade.*": ("某品阶总量上限", "整数"),
    "total_feed_cap_by_species": ("物种总量上限", "species→上限"),
    "total_feed_cap_by_species.*": ("某物种总量上限", "整数"),
    "items.*.per_item_cap": ("单药喂养上限", "该丹最多次数"),
    "items.*.effects": ("单次喂养效果", "flat_atk 等"),
    "items.*.effects.*": ("单项效果值", "数值"),
    "items.*.summary": ("兽丹摘要", "说明"),
    # ---- pet_encounter ----
    "capturable_types": ("可捕类型", "如 spirit_beast"),
    "skip_battle": ("跳过战斗", "占位区直接可捕"),
    "tables": ("遭遇表", "region×时辰×天气"),
    "tables.*.region_id": ("区域", "map region 或 *"),
    "tables.*.shichen": ("时辰", "id 或 *"),
    "tables.*.weather": ("天气", "id 或 *"),
    "tables.*.entries": ("条目", "加权遇敌列表"),
    "tables.*.entries.*.type": ("遇敌类型", "spirit_beast/monster"),
    "tables.*.entries.*.species_id": ("物种", "可捕时必填"),
    "tables.*.entries.*.weight": ("权重", "整数"),
    "tables.*.entries.*.grade_weights": ("品阶权重", "grade→权重"),
    # ---- pet_capture ----
    "lure_item_id": ("诱灵草", "inventory item_id"),
    "bag_item_id": ("灵兽袋", "inventory item_id"),
    "require_bag": ("必须持袋", "无袋拒绝"),
    "daily_attempt_cap": ("日尝试上限", "0=不限"),
    "special_affix_min_tier": ("特殊词条门槛", "默认 rare"),
    "pen_affix": ("词条惩罚", "每条减成"),
    "pen_grade": ("品阶惩罚", "grade→减成"),
    "realm_diff": ("修为差配置", "per_stage/clamp"),
    "root_affinity": ("灵根亲和", "tag→race→加成"),
    "taming_tech_bonus": ("御兽功法", "technique→加成"),
    "species_capture_override": ("物种捕获率", "覆盖种族基率"),
    "auto_capture": ("自动捕", "enabled/max_rolls"),
    "estimate_special_affixes": ("估计特殊词条", "遭遇抽样"),
    # ---- items / inventory ----
    "stack_rules": ("堆叠规则", "默认与按类型堆叠上限"),
    "stack_rules.default_max_stack": ("默认堆叠上限", "未单独指定时的上限"),
    "stack_rules.by_item_type": ("按类型堆叠", "item_type → 上限"),
    "stack_rules.by_item_type.*": ("某类型堆叠上限", "覆盖默认堆叠"),
    "item_types": ("物品类型枚举", "系统识别的 item_type 列表"),
    "items": ("道具目录", "物品 id → 定义"),
    "items.*": ("道具条目", "单个物品定义"),
    "items.*.name": ("展示名", "玩家可见物品名"),
    "items.*.item_type": ("物品类型", "须在 item_types 内"),
    "items.*.max_stack": ("堆叠上限", "该物品最大堆叠"),
    "items.*.bag_allowed": ("可入袋类型", "normal / reincarnation 等"),
    "items.*.use_effect": ("使用效果", "消耗品效果对象"),
    "items.*.use_effect.kind": ("效果种类", "效果类标识"),
    "items.*.use_effect.amount": ("效果数值", "效果强度"),
    "items.*.use_effect.book_id": ("技能书 ID", "对应 pet_skill_books.books"),
    "items.*.description": ("说明", "运营/玩家说明"),
    # ---- techniques ----
    "techniques": ("功法表", "technique_id → 定义"),
    "techniques.*": ("功法条目", "单条功法"),
    "techniques.*.name": ("展示名", "玩家可见功法名"),
    "techniques.*.track": ("轨道", "spirit / body / crafting"),
    "techniques.*.max_level": ("最大等级", "可升到的最高级"),
    "techniques.*.env_tags": ("环境标签", "参与时辰/天气 tag 乘区"),
    "techniques.*.traits": ("特性", "如 reincarnatable 可轮回带入"),
    "techniques.*.cost_per_level": ("每级消耗", "下标 0=升到 1 级的灵石等"),
    "techniques.*.effects_placeholder": ("效果占位", "战力/挂机加成占位对象"),
    "techniques.*.effects_placeholder.atk_bonus_per_level": ("每级攻击加成", "占位"),
    "techniques.*.effects_placeholder.hp_bonus_per_level": ("每级生命加成", "占位"),
    "techniques.*.dice_mods": ("骰子修正表", "按等级的 min/max_bonus"),
    "techniques.*.dice_mods.*.min_bonus": ("下限加成", "该级对骰子下限修正"),
    "techniques.*.dice_mods.*.max_bonus": ("上限加成", "该级对骰子上限修正"),
    # ---- weather ----
    "regions": ("区域天气/地图", "区域 id → 配置"),
    "regions.*": ("区域条目", "单个区域"),
    "regions.*.pool": ("天气滚动池", "天气 id → 权重"),
    "regions.*.pool.*": ("池内权重", "该天气相对权重"),
    "regions.*.roll_interval_seconds": ("重掷间隔秒", "重新掷天气的间隔"),
    "regions.*.name": ("区域名", "玩家可见区域名"),
    "regions.*.weather_region": ("天气池键", "通常与区域 id 相同"),
    "regions.*.summary": ("区域简介", "玩家可见"),
    "regions.*.connections": ("邻接区域", "region_id 列表"),
    "labels": ("展示名表", "id → 中文展示名"),
    "labels.*": ("单项展示名", "单个 id 的中文名"),
    "catalog": ("玩家可见说明目录", "id → 文案对象"),
    "catalog.*": ("说明条目", "单个天气/时辰说明"),
    "catalog.*.summary": ("总述", "玩家可见一句话"),
    "catalog.*.idle_note": ("修炼说明", "挂机相关文案"),
    "catalog.*.spawn_bias_note": ("刷怪说明", "遭遇权重文案"),
    "catalog.*.craft_notes": ("工坊说明", "各工坊分支文案"),
    "catalog.*.craft_notes.*": ("工坊分支说明", "alchemy/smithing 等"),
    "catalog.*.tribulation_note": ("渡劫说明", "渡劫压力文案"),
    "catalog.*.breakthrough_note": ("突破说明", "突破检定文案"),
    "modifiers": ("数值乘区", "结算用乘区表"),
    "modifiers.idle_cultivation": ("挂机修炼乘区", "天气/时辰 → 挂机修为倍率"),
    "modifiers.idle_cultivation.*": ("某键挂机乘区", "该天气或时辰的挂机倍率"),
    "modifiers.battle_cultivation": ("开战修为乘区", "开战奖励修为倍率"),
    "modifiers.battle_cultivation.*": ("某键开战乘区", "该天气或时辰的开战修为倍率"),
    "modifiers.craft": ("工坊乘区", "分支 → 天气/时辰 → 倍率"),
    "modifiers.craft.*": ("工坊分支乘区表", "某工坊分支下的乘区"),
    "modifiers.craft.*.*": ("某键工坊乘区", "该分支在该天气/时辰的倍率"),
    "modifiers.tribulation_pressure": ("渡劫压力乘区", "越高渡劫越痛"),
    "modifiers.tribulation_pressure.*": ("某键渡劫压力", "该天气的压力系数"),
    "modifiers.breakthrough_success": ("突破成功乘区", "突破概率相关倍率"),
    "modifiers.breakthrough_success.*": ("某键突破乘区", "该天气/时辰的突破倍率"),
    "modifiers.spawn_bias": ("刷怪权重乘区", "天气 → 妖兽标签权重"),
    "modifiers.spawn_bias.*": ("某天气刷怪表", "该天气下的标签权重"),
    "modifiers.spawn_bias.*.*": ("某标签刷怪权重", "相对权重倍率"),
    "tag_modifiers": ("标签乘区", "灵根/功法标签额外乘区"),
    "tag_modifiers.*": ("标签乘区通道", "如 idle_cultivation"),
    "tag_modifiers.*.by_weather": ("按天气标签乘区", "天气 → tag → 倍率"),
    "tag_modifiers.*.by_weather.*": ("某天气标签表", "该天气下的 tag 乘区"),
    "tag_modifiers.*.by_weather.*.*": ("单标签倍率", "某 env_tag 的倍率"),
    "tag_modifiers.*.by_shichen": ("按时辰标签乘区", "时辰 → tag → 倍率"),
    "tag_modifiers.*.by_shichen.*": ("某时辰标签表", "该时辰下的 tag 乘区"),
    "tag_modifiers.*.by_shichen.*.*": ("单标签倍率", "某 env_tag 的倍率"),
    "tag_modifiers.*.*": ("标签乘区组", "兼容旧结构"),
    "environment_counters": ("环境克制表", "环境层对抗"),
    "environment_counters.*": ("某环境克制行", "对其他环境的乘区表"),
    "environment_counters.*.*": ("克制乘区", "A 对 B 的 counter_mul"),
    "weather_counters": ("天气克制表", "天气层对抗"),
    "weather_counters.*": ("某天气克制行", "对其他天气的乘区"),
    "weather_counters.*.*": ("天气克制乘区", "counter_mul"),
    "effect_counters": ("效果克制表", "效果层对抗"),
    "effect_counters.*": ("某效果克制行", "对其他效果的乘区"),
    "effect_counters.*.*": ("效果克制乘区", "counter_mul"),
    "monsters.*.max_rounds": ("回合上限", "本场战斗最大回合数"),
    "monsters.*.stamina_cost": ("体力消耗", "开战消耗体力；缺省读 stamina.yaml"),
    "monsters.*.rewards_on_win": ("胜利奖励", "修为/灵石等"),
    "monsters.*.rewards_on_win.cultivation_points": ("胜：修为", "胜利获得修为"),
    "monsters.*.rewards_on_win.spirit_stones": ("胜：灵石", "胜利获得灵石"),
    "monsters.*.rewards_on_lose": ("失败奖励", "失败安慰奖"),
    "monsters.*.rewards_on_lose.cultivation_points": ("败：修为", "失败获得修为"),
    "monsters.*.rewards_on_lose.spirit_stones": ("败：灵石", "失败获得灵石"),
    "monsters.*.units": ("多棋子编队", "单位列表；无则单体回退"),
    "monsters.*.units.*": ("棋子单位", "单个敌方棋子"),
    "monsters.*.units.*.unit_uid": ("单位 UID", "编队内唯一 id"),
    "monsters.*.units.*.name": ("单位名", "展示名"),
    "monsters.*.units.*.x": ("坐标 X", "敌对半区 4～6"),
    "monsters.*.units.*.y": ("坐标 Y", "棋盘行"),
    "monsters.*.units.*.atk": ("单位攻击", "整数"),
    "monsters.*.units.*.hp": ("单位生命", "整数"),
    "monsters.*.units.*.speed": ("单位速度", "先攻"),
    "monsters.*.units.*.attack_range": ("攻击距离", "格数"),
    "monsters.*.units.*.attack_kind": ("攻击类型", "melee_physical / ranged_magic 等"),
    "monsters.*.units.*.can_fly": ("可否飞行", "布尔"),
    "monsters.*.units.*.taunt_aura_id": (
        "嘲讽光环",
        "外键 → taunt_auras.auras；空=无",
    ),
    "schema_version": ("结构版本", "配置 schema 版本号"),
    "auras": ("光环表", "aura_id → 嘲讽光环定义"),
    "auras.*": ("光环条目", "单个嘲讽光环"),
    "auras.*.label_zh": ("中文名", "面板与战报"),
    "auras.*.help_zh": ("运营说明", "后台编辑提示"),
    "auras.*.summary": ("玩家摘要", "短描述范围"),
    "auras.*.shape": ("形状", "ortho_adjacent / chebyshev / offsets"),
    "auras.*.radius": ("半径", "仅 chebyshev"),
    "auras.*.cells": ("偏移表", "仅 offsets；[{dx,dy}]"),
    "auras.*.include_self_cell": ("含自身格", "默认否"),
    "auras.*.duration_rounds": ("持续回合", "空=直到死亡"),
    # ---- formations ----
    "formations.*.level": ("阵法等级", "整数等级"),
    "formations.*.unlocked_by_default": ("默认解锁", "创角是否已解锁"),
    "formations.*.required_array_level": ("所需阵法钻研", "可选门槛"),
    "formations.*.terrain": ("地形列表", "障碍/深渊/禁制等"),
    "formations.*.terrain.*": ("地形格", "单格地形定义"),
    "formations.*.terrain.*.x": ("地形 X", "己方半区 0～2"),
    "formations.*.terrain.*.y": ("地形 Y", "棋盘行"),
    "formations.*.terrain.*.type": ("地形类型", "obstacle障碍 / ravine深渊 / seal禁制"),
    "formations.*.terrain.*.subtype": (
        "地形子类",
        "障:destructible/indestructible；渊:flyable/no_fly；禁:ranged_physical/ranged_magic/ranged_all",
    ),
    "formations.*.deploy": ("部署契约", "mode/cells/max_units 等；定稿时写死"),
    "formations.*.deploy.mode": ("部署模式", "default / fixed / free_own / mask"),
    "formations.*.deploy.max_units": ("阵法上阵上限", "可选；与境界/格数取 min"),
    "formations.*.deploy.cells": ("固定或掩码格", "fixed/mask 必填"),
    "formations.*.deploy.add_cells": ("追加可部署格", "default/fixed 可用"),
    "formations.*.deploy.exclude_cells": ("排除格", "从有效区扣除"),
    "formations.*.deploy.allow_neutral": ("允许中立列", "默认 false；高危"),
    "formations.*.terrain_layout": ("地形布局模式", "none / fixed / brush"),
    "formations.*.terrain_layout.mode": ("地形模式", "出战不改地形；brush 仅定稿"),
    "formations.*.force_shifts": ("开战强制移位", "from/to 进攻方视角敌区坐标"),
    "formations.*.force_shifts.*.from": ("移位源格", "[x,y]"),
    "formations.*.force_shifts.*.to": ("移位目标格", "[x,y]"),
    "formations.*.force_shifts.*.only_kinds": ("种类过滤", "可选；空=任意对方棋子"),
    "formations.*.environment": ("环境层", "迷雾等；可为 null"),
    "formations.*.environment.id": ("环境 id", "如 mist"),
    "formations.*.environment.force_apply": ("强制落地", "true=跳过对抗"),
    "formations.*.environment.counter_group": ("克制分组", "环境对抗键"),
    "formations.*.weather": ("天气层", "阵法天气；可为 null"),
    "formations.*.weather.id": ("天气层 id", "阵法声明的天气"),
    "formations.*.weather.force_apply": ("天气强制落地", "布尔"),
    "formations.*.effect": ("效果层", "守势等；可为 null"),
    "formations.*.effect.id": ("效果 id", "如 guarded"),
    "formations.*.effect.force_apply": ("效果强制落地", "布尔"),
    "formations.*.effect.atk_mul": ("攻击乘区", "效果层攻击倍率"),
    "formations.*.effect.hp_mul": ("生命乘区", "效果层生命倍率"),
    "environment_counters": ("环境克制表", "环境层对抗"),
    "weather_counters": ("天气克制表", "天气层对抗"),
    "effect_counters": ("效果克制表", "效果层对抗"),
    "environment_catalog": ("环境目录", "id→中文名与 combat 载荷"),
    "environment_catalog.*.label_zh": ("环境中文名", "战报/UI 展示"),
    "environment_catalog.*.summary": ("环境摘要", "玩家可读说明"),
    "environment_catalog.*.combat": ("环境战斗载荷", "ranged_hit_mul 等"),
    "environment_catalog.*.combat.ranged_hit_mul": ("远程命中乘区", "默认 1.0"),
    "environment_catalog.*.combat.physical_damage_mul": ("物理伤害乘区", "默认 1.0"),
    "environment_catalog.*.combat.magic_damage_mul": ("法术伤害乘区", "默认 1.0"),
    "weather_catalog": ("阵法天气目录", "≠世界天气；id→中文名与 combat"),
    "weather_catalog.*.label_zh": ("天气中文名", "战报/UI 展示"),
    "weather_catalog.*.summary": ("天气摘要", "玩家可读说明"),
    "weather_catalog.*.combat": ("天气战斗载荷", "乘区对象"),
    "effect_catalog": ("效果目录", "id→中文名（面板乘区仍在阵法行）"),
    "effect_catalog.*.label_zh": ("效果中文名", "战报/UI 展示"),
    "effect_catalog.*.summary": ("效果摘要", "玩家可读说明"),
    # techniques extra
    "techniques.*.effects_placeholder.crafting_speed_bonus_per_level": (
        "每级制造速度加成",
        "制造轨道功法占位",
    ),
    # ---- calendar ----
    "slot_seconds": ("时辰槽秒数", "每个时辰持续现实秒数"),
    "epoch_utc": ("历法纪元", "UTC 起点，与 slot 共同决定时辰"),
    "shichen_order": ("时辰顺序", "六个时辰 id 的循环列表"),
    # ---- monsters ----
    "monsters": ("怪物表", "monster_id → 定义"),
    "monsters.*": ("怪物条目", "单个怪物模板"),
    "monsters.*.name": ("展示名", "玩家可见怪名"),
    "monsters.*.hp": ("生命", "基础生命"),
    "monsters.*.atk": ("攻击", "基础攻击"),
    "monsters.*.realm_hint": ("境界提示", "展示用境界描述"),
    "monsters.*.speed": ("速度", "先攻相关"),
    "monsters.*.dice_bounds": ("骰子区间", "怪物检定上下限"),
    # ---- formations ----
    "formations": ("阵法表", "formation_id → 定义"),
    "formations.*": ("阵法条目", "单个阵法"),
    "formations.*.name": ("展示名", "阵法名"),
    "formations.*.enabled": ("是否启用", "关闭则不可选"),
    "formations.*.slots": ("站位配置", "阵位 JSON"),
    "formations.*.summary": ("简介", "玩家可见说明"),
    # ---- sects ----
    "facilities": ("设施表", "设施 id → 开关与说明"),
    "facilities.*": ("设施条目", "单个设施"),
    "facilities.*.enabled": ("是否开放", "false 时玩家入口未开放"),
    "facilities.*.note": ("设施说明", "玩家可见说明"),
    "create_cost_spirit_stones": ("建宗灵石", "自建宗门费用"),
    "idle_bonus_vs_wanderer": ("入宗挂机乘区", "相对散修占位乘区"),
    "contribution_zero_on_reincarnation": ("轮回归零贡献", "入轮回是否清贡献"),
    "npc_sects": ("NPC 宗门表", "template_id → 拜入条件"),
    "npc_sects.*": ("NPC 宗门", "单个模板"),
    "npc_sects.*.label_zh": ("宗门中文名", "玩家可见"),
    "npc_sects.*.join_min_realm": ("拜入最低大境界", "机读键如 jindan"),
    "npc_sects.*.join_cost_spirit_stones": ("拜入灵石", "可为 0"),
    "features_by_founder_realm": ("祖师境界功能", "大境界 → 功能键列表"),
    "sect_exchange": ("兑宠规则", "白名单与贡献费"),
    "sect_exchange.whitelist_species": ("兑宠白名单", "物种 id 列表"),
    "sect_exchange.cost_contribution": ("兑宠贡献费", "整数"),
    "shop_items": ("贡献商店", "条目 → 费用与奖励"),
    "quests": ("宗门任务", "任务 → 接取方与奖励"),
    "sects": ("宗门模板", "宗门 id → 占位模板"),
    "sects.*": ("宗门条目", "单个宗门模板"),
    "sects.*.name": ("宗门名", "展示名"),
    "sects.*.facilities": ("关联设施", "设施 id 列表"),
    "sects.*.summary": ("宗门简介", "玩家可见"),
    # ---- map ----
    "factions": ("势力元数据", "M9 势力着色占位"),
    # ---- activity ----
    "activities": ("活动表", "activity_id → 定义"),
    "activities.*": ("活动条目", "单个活动"),
    "activities.*.enabled": ("是否生效", "运营开关"),
    "activities.*.title": ("活动标题", "展示名"),
    "activities.*.note": ("活动说明", "玩家可见"),
    "activities.*.overrides": ("覆盖提示", "指向其它域的提示性说明"),
    # ---- realms ----
    "major_realms": ("大境界表", "大境界 id → 定义"),
    "major_realms.*": ("大境界条目", "单个大境界"),
    "major_realms.*.name": ("展示名", "如锻体/炼气"),
    "major_realms.*.stage_mode": ("阶段模式", "layers 或 phases"),
    "major_realms.*.next_major": ("下一大境", "链上下一境 id；终点 null"),
    "major_realms.*.stages": ("小层列表", "层/阶段数组"),
    "major_realms.*.stages.*.stage": ("层编号", "整数层号"),
    "major_realms.*.stages.*.label": ("层标签", "layer_N / early 等"),
    "major_realms.*.stages.*.cultivation_required": ("修为门槛", "升到本层累计修为"),
    "major_realms.*.stages.*.base_atk": ("基础攻击", "战力占位"),
    "major_realms.*.stages.*.base_hp": ("基础生命", "战力占位"),
    "body_temper_unlock_majors": ("炼体对照主修序", "锻体→大乘解锁链（可含未开放）"),
    "body_temper_majors": ("炼体大境表", "炼皮→道体含层/期"),
    "body_temper_majors.*": ("炼体大境条目", "单档炼体境"),
    "body_temper_majors.*.name": ("展示名", "如炼皮/锻骨"),
    "body_temper_majors.*.stage_mode": ("阶段模式", "layers 或 phases"),
    "body_temper_majors.*.unlock_major": ("对照主修", "须在对照序中"),
    "body_temper_majors.*.next_major": ("下一炼体境", "扩境口；终点 null"),
    "body_temper_majors.*.stages": ("层/期列表", "progress_required 门槛"),
    "body_temper_quench": ("淬体规则", "成功率与失败保留比"),
    "body_temper_quench.layer_advance": ("层进阶规则", "同境淬体"),
    "body_temper_quench.major_advance": ("跨境规则", "炼体大境晋级"),
    "body_temper_major_order": ("炼体对照主修序(旧)", "兼容旧键"),
    "body_temper_stages": ("炼体九境表(旧)", "兼容旧键"),
    # ---- idle ----
    "tick_seconds": ("Tick 秒数", "每次挂机结算墙钟秒"),
    "spirit_stone_cost_by_realm": ("灵石消耗表", "大境界 → 每 tick 灵石"),
    "spirit_stone_cost_by_realm.*": ("某境灵石消耗", "该大境界每 tick 消耗"),
    "directions": ("挂机三向", "spirit/body/crafting"),
    "directions.*": ("方向条目", "单个挂机方向"),
    "directions.*.enabled": ("方向是否开放", "关闭则不可选"),
    "directions.*.cultivation_per_tick": ("灵修回落速率", "未命中境界表时每 tick 修为"),
    "directions.*.body_tempering_per_tick": ("体修回落速率", "未命中境界表时每 tick 锻体"),
    "directions.*.crafting_exp_per_tick": ("制造回落速率", "未命中境界表时每 tick 制造经验"),
    "gain_per_tick_by_realm": ("境界基础产出", "方向 × 大境界 → 产出"),
    "gain_per_tick_by_realm.*": ("某方向产出表", "大境界 → 每 tick"),
    "gain_per_tick_by_realm.*.*": ("某境产出", "该方向该境每 tick 整数"),
    "bonus_channels": ("加成/修正通道", "通道 id → 开关与默认值"),
    "bonus_channels.*": ("通道条目", "单个通道"),
    "bonus_channels.*.enabled": ("通道是否启用", "false 时不参与"),
    "bonus_channels.*.default_mult": ("默认倍率", "无实例时的倍率"),
    "clamp_min": ("乘区下限", "通道乘积下限"),
    "clamp_max": ("乘区上限", "通道乘积上限"),
    "clamp.min": ("环境乘区下限", "calendar/weather 环境乘区钳制下限"),
    "clamp.max": ("环境乘区上限", "calendar/weather 环境乘区钳制上限"),
    # ---- dice ----
    "fallback_bounds": ("回落上下限", "无境界上下文时使用"),
    "fallback_bounds.min": ("回落下限", "骰子最小值"),
    "fallback_bounds.max": ("回落上限", "骰子最大值"),
    "monster_default": ("怪物默认区间", "PVE 防守侧默认"),
    "monster_default.min": ("怪物下限", "默认 min"),
    "monster_default.max": ("怪物上限", "默认 max"),
    "clamp": ("全局钳制", "绝对上下限"),
    "clamp.absolute_min": ("绝对下限", "不低于此值"),
    "clamp.absolute_max": ("绝对上限", "不高于此值"),
    "breakthrough": ("突破选项", "突破检定相关开关"),
    "breakthrough.use_legacy_success_rate": ("沿用突破成功率", "true=用 breakthrough.yaml 映射"),
    "combat": ("战斗选项", "战斗检定相关开关"),
    "combat.use_midpoint_normalizer": ("中点正态化", "伤害因子=roll/mid"),
    "purposes": ("用途清单", "breakthrough/combat 等"),
    # ---- breakthrough.yaml 域（M5-D05）----
    "layer_advance": ("层进阶规则", "同境内层/期"),
    "layer_advance.success_rate": ("层进阶成功率", "0～1"),
    "layer_advance.spirit_stone_cost": ("层进阶灵石", "每次尝试"),
    "layer_advance.fail_cultivation_keep_ratio": ("失败保留修为比", "0～1"),
    "layer_advance.fail_still_charge_stones": ("失败仍扣灵石", "布尔"),
    "major_advance": ("跨境规则", "跨大境界"),
    "major_advance.success_rate": ("跨境成功率", "0～1"),
    "major_advance.spirit_stone_cost": ("跨境灵石", "每次尝试"),
    "major_advance.fail_cultivation_keep_ratio": ("跨境失败保留修为比", "0～1"),
    "major_advance.fail_still_charge_stones": ("跨境失败仍扣灵石", "布尔"),
    "success_rate_clamp": ("成功率钳制", "min/max"),
    "success_rate_clamp.min": ("成功率下限", "含轮回加成后"),
    "success_rate_clamp.max": ("成功率上限", "含轮回加成后"),
    "pre_foundation_free": (
        "筑基前突破免费",
        "true=锻体/炼气不扣石；仅炼气圆满→筑基扣费；与轮回无关",
    ),
    "async_channel": ("异步真读条（可选）", "默认关闭；开启后走闭关占用"),
    "async_channel.enabled": (
        "启用真读条",
        "产品默认 false：点击突破同步出结果；true=闭关读条",
    ),
    "async_channel.label_zh": ("读条中文名", "玩家可见"),
    "async_channel.hint_zh": ("读条提示", "玩家可见说明"),
    "async_channel.duration_seconds": ("读条时长表", "layer_advance/major_advance 秒"),
    "async_channel.duration_seconds.layer_advance": ("层进阶读条秒", "权威墙钟秒"),
    "async_channel.duration_seconds.major_advance": ("跨境读条秒", "权威墙钟秒"),
    "async_channel.client_poll_ms": ("前端轮询建议毫秒", "仅提示；权威 ends_at"),
    # ---- dao_lord / contest ----
    "claim_min_level": ("空位就任最低道等级", "达标自动就任"),
    "challenge_min_level": ("挑战/报名最低道等级", "道主之争报名门槛"),
    "cooldown": ("挑战冷却", "win/lose/abort 秒数"),
    "cooldown.win_seconds": ("胜方冷却秒", "挑战胜利后冷却"),
    "cooldown.lose_seconds": ("负方冷却秒", "挑战失败后冷却"),
    "cooldown.abort_seconds": ("弃权冷却秒", "中途退出冷却"),
    "reconnect_grace_seconds": ("断线宽限秒", "挑战者重连窗口"),
    "missing_snapshot_policy": ("无快照策略", "reject | weak_npc"),
    "privileges_default": ("道主特权默认", "就任写入"),
    "windows": ("旧开窗列表", "过渡兼容；赛会以 contest 为准"),
    "single_challenge_per_dao": ("单道同时一战", "过渡单挑"),
    "contest": ("道主之争赛会", "报名窗与开打时刻等"),
    "contest.tz": ("赛会时区", "如 Asia/Shanghai"),
    "contest.registration_start": ("报名开始时刻", "每日 HH:MM"),
    "contest.registration_end": ("报名结束时刻", "每日 HH:MM"),
    "contest.fight_at": ("开打时刻", "每日 HH:MM；到点匹配"),
    "contest.live_round_kinds": ("可直播轮次", "semi/final/lord"),
    "contest.live_prep_seconds": ("直播准备秒数", "入席倒计时"),
    "contest.live_playback_seconds": ("对战直播秒数", "准备后节拍窗"),
    "contest.live_tick_base_ms": ("普通事件间隔毫秒", "直播节拍"),
    "contest.live_dramatic_pause_ms": ("关键停顿毫秒", "阵亡/结束等"),
    "contest.log_retain_until_next_contest": ("日志保留至下场", "下场开赛清回溯"),
    "contest.both_offline_policy": ("双离线策略", "earlier_entrant_advances 等"),
    "contest.dev_assume_online": ("DEV 假定在线", "生产须 false"),
    "fate_luck_tiers": ("气运分档", "luck 区间 → bonus 列表"),
    "fate_luck_tiers.*.min_luck": ("气运下限", "含"),
    "fate_luck_tiers.*.max_luck": ("气运上限", "含"),
    "fate_luck_tiers.*.min_bonus": ("下限加成", "整数"),
    "fate_luck_tiers.*.max_bonus": ("上限加成", "整数"),
    "body_realm_bonus": ("体修境界加成", "大境×小境 → bonus"),
    "body_realm_bonus.*": ("某大体修加成表", "小境 → bonus"),
    "body_realm_bonus.*.*": ("某层体修加成", "min_bonus/max_bonus"),
    "body_realm_bonus.*.*.min_bonus": ("体修下限加成", "加到骰子 min"),
    "body_realm_bonus.*.*.max_bonus": ("体修上限加成", "加到骰子 max"),
    "realm_bounds": ("境界默认上下限", "权威检定表"),
    "realm_bounds.*": ("某大境上下限表", "小境 → min/max"),
    "realm_bounds.*.*": ("某层上下限", "min/max 对象"),
    "realm_bounds.*.*.min": ("检定下限", "该层骰子最小值"),
    "realm_bounds.*.*.max": ("检定上限", "该层骰子最大值"),
}


def _match_help(path: str) -> tuple[str, str] | None:
    """精确或通配匹配中文说明。"""
    if path in _PATH_HELP:
        return _PATH_HELP[path]
    parts = path.split(".")
    for pattern, help_pair in _PATH_HELP.items():
        pat_parts = pattern.split(".")
        if len(pat_parts) != len(parts):
            continue
        ok = True
        for left, right in zip(pat_parts, parts, strict=True):
            if left == "*":
                continue
            if left != right:
                ok = False
                break
        if ok:
            return help_pair
    # 数组元素路径 foo.bar.* ：回落到父级说明
    if parts and parts[-1] == "*" and len(parts) > 1:
        parent = ".".join(parts[:-1])
        parent_help = _match_help(parent)
        if parent_help:
            return (f"{parent_help[0]}·元素", f"列表/表中的单项；{parent_help[1]}")
    return None


def _walk(
    node: Any,
    prefix: str,
    out: list[dict[str, Any]],
    *,
    max_depth: int = 8,
) -> None:
    """递归展开可配置路径。"""
    if max_depth < 0:
        return
    help_pair = _match_help(prefix) if prefix else None
    label_zh, help_zh = help_pair if help_pair else ("（未命名字段）", "待补中文说明 — 请在 admin_field_catalog 登记")
    documented = help_pair is not None

    if isinstance(node, dict):
        if prefix:
            out.append(
                {
                    "path": prefix,
                    "label_zh": label_zh,
                    "help_zh": help_zh,
                    "value_kind": "object",
                    "documented": documented,
                    "sample": None,
                },
            )
        for key, value in node.items():
            child = f"{prefix}.{key}" if prefix else str(key)
            _walk(value, child, out, max_depth=max_depth - 1)
        return

    if isinstance(node, list):
        if prefix:
            out.append(
                {
                    "path": prefix,
                    "label_zh": label_zh,
                    "help_zh": help_zh,
                    "value_kind": "array",
                    "documented": documented,
                    "sample": f"len={len(node)}",
                },
            )
        # 用 * 代表数组元素路径，便于匹配 *.min_bonus 等
        if node:
            _walk(node[0], f"{prefix}.*", out, max_depth=max_depth - 1)
        return

    # 标量叶
    if prefix:
        sample: Any = node
        if isinstance(sample, str) and len(sample) > 80:
            sample = sample[:77] + "..."
        out.append(
            {
                "path": prefix,
                "label_zh": label_zh,
                "help_zh": help_zh,
                "value_kind": type(node).__name__,
                "documented": documented,
                "sample": sample,
            },
        )


def build_field_catalog(payload: dict[str, Any]) -> list[dict[str, Any]]:
    """
    展开配置根，返回全部可配置路径及中文说明。

    Args:
        payload: 域 effective / YAML 根。

    Returns:
        list[dict]: 含 path / label_zh / help_zh / documented。
    """
    rows: list[dict[str, Any]] = []
    if not isinstance(payload, dict):
        return rows
    _walk(payload, "", rows)
    # 去掉空 path
    return [row for row in rows if row.get("path")]


def catalog_coverage(catalog: list[dict[str, Any]]) -> dict[str, Any]:
    """统计中文说明覆盖率。"""
    total = len(catalog)
    documented = sum(1 for row in catalog if row.get("documented"))
    return {
        "total_paths": total,
        "documented_paths": documented,
        "undocumented_paths": total - documented,
        "coverage_ratio": round(documented / total, 4) if total else 1.0,
    }
