"""工坊品质、制作等级与配方筛选协议常量。"""

from __future__ import annotations

from typing import Final

from app.constants.equipment import (
    CATALOG_KIND_ACCESSORY,
    CATALOG_KIND_ACCESSORY_ANY,
    CATALOG_KIND_FABAO,
    CATALOG_KIND_FABAO_ANY,
    CATALOG_KIND_LINGBAO,
    CATALOG_KIND_RING,
    CATALOG_KIND_RING_ANY,
    CATALOG_KIND_WEAPON_1H,
    CATALOG_KIND_WEAPON_ANY,
    EQUIP_KIND_WEAPON_2H,
    EQUIPMENT_SLOT_ACCESSORY_1,
    EQUIPMENT_SLOT_ACCESSORY_2,
    EQUIPMENT_SLOT_ARMOR_CHEST,
    EQUIPMENT_SLOT_ARMOR_HANDS,
    EQUIPMENT_SLOT_ARMOR_HEAD,
    EQUIPMENT_SLOT_ARMOR_LEGS,
    EQUIPMENT_SLOT_ARMOR_SHOES,
    EQUIPMENT_SLOT_FABAO_1,
    EQUIPMENT_SLOT_FABAO_2,
    EQUIPMENT_SLOT_FUBAO,
    EQUIPMENT_SLOT_NATAL_FABAO,
    EQUIPMENT_SLOT_RING_1,
    EQUIPMENT_SLOT_RING_2,
    EQUIPMENT_SLOT_WEAPON_1,
    EQUIPMENT_SLOT_WEAPON_2,
    canonical_equipment_slot,
)

# 造物品质（机读；展示用 CRAFT_QUALITY_LABEL_ZH）
CRAFT_QUALITY_COMMON: Final[str] = "common"  # 凡品
CRAFT_QUALITY_FINE: Final[str] = "fine"  # 良品
CRAFT_QUALITY_RARE: Final[str] = "rare"  # 上品
CRAFT_QUALITY_SUPERB: Final[str] = "superb"  # 极品

CRAFT_QUALITIES: Final[tuple[str, ...]] = (
    CRAFT_QUALITY_COMMON,
    CRAFT_QUALITY_FINE,
    CRAFT_QUALITY_RARE,
    CRAFT_QUALITY_SUPERB,
)

CRAFT_QUALITY_LABEL_ZH: Final[dict[str, str]] = {
    CRAFT_QUALITY_COMMON: "凡品",
    CRAFT_QUALITY_FINE: "良品",
    CRAFT_QUALITY_RARE: "上品",
    CRAFT_QUALITY_SUPERB: "极品",
}

# 制作等级不足（开工拒绝）
ERR_CRAFT_LEVEL: Final[int] = 40086
ERR_CRAFT_LEVEL_ZH: Final[str] = "制作等级不足，无法学习或制造该图纸"

# 阵法等非制造业配方不可开工
ERR_CRAFT_NOT_WORKSHOP: Final[int] = 40087
ERR_CRAFT_NOT_WORKSHOP_ZH: Final[str] = "阵法不属于工坊制造业"

# 炼器配方栏「部位」筛选（玩法分组，不是 17 区指针槽本身）
CRAFT_EQUIP_SLOT_GROUP_WEAPON: Final[str] = "weapon"  # 武器
CRAFT_EQUIP_SLOT_GROUP_HEAD: Final[str] = "head"  # 头部
CRAFT_EQUIP_SLOT_GROUP_CHEST: Final[str] = "chest"  # 胸甲
CRAFT_EQUIP_SLOT_GROUP_HANDS: Final[str] = "hands"  # 护手
CRAFT_EQUIP_SLOT_GROUP_LEGS: Final[str] = "legs"  # 腿甲
CRAFT_EQUIP_SLOT_GROUP_SHOES: Final[str] = "shoes"  # 鞋履
CRAFT_EQUIP_SLOT_GROUP_ACCESSORY: Final[str] = "accessory"  # 饰品
CRAFT_EQUIP_SLOT_GROUP_FABAO: Final[str] = "fabao"  # 法宝

CRAFT_EQUIP_SLOT_GROUPS: Final[tuple[str, ...]] = (
    CRAFT_EQUIP_SLOT_GROUP_WEAPON,
    CRAFT_EQUIP_SLOT_GROUP_HEAD,
    CRAFT_EQUIP_SLOT_GROUP_CHEST,
    CRAFT_EQUIP_SLOT_GROUP_HANDS,
    CRAFT_EQUIP_SLOT_GROUP_LEGS,
    CRAFT_EQUIP_SLOT_GROUP_SHOES,
    CRAFT_EQUIP_SLOT_GROUP_ACCESSORY,
    CRAFT_EQUIP_SLOT_GROUP_FABAO,
)

CRAFT_EQUIP_SLOT_GROUP_LABELS_ZH: Final[dict[str, str]] = {
    CRAFT_EQUIP_SLOT_GROUP_WEAPON: "武器",
    CRAFT_EQUIP_SLOT_GROUP_HEAD: "头部",
    CRAFT_EQUIP_SLOT_GROUP_CHEST: "胸甲",
    CRAFT_EQUIP_SLOT_GROUP_HANDS: "护手",
    CRAFT_EQUIP_SLOT_GROUP_LEGS: "腿甲",
    CRAFT_EQUIP_SLOT_GROUP_SHOES: "鞋履",
    CRAFT_EQUIP_SLOT_GROUP_ACCESSORY: "饰品",
    CRAFT_EQUIP_SLOT_GROUP_FABAO: "法宝",
}

# equipment.yaml slot / equip_kind → 工坊部位组
CRAFT_EQUIP_SLOT_TO_GROUP: Final[dict[str, str]] = {
    EQUIPMENT_SLOT_WEAPON_1: CRAFT_EQUIP_SLOT_GROUP_WEAPON,
    EQUIPMENT_SLOT_WEAPON_2: CRAFT_EQUIP_SLOT_GROUP_WEAPON,
    CATALOG_KIND_WEAPON_1H: CRAFT_EQUIP_SLOT_GROUP_WEAPON,
    CATALOG_KIND_WEAPON_ANY: CRAFT_EQUIP_SLOT_GROUP_WEAPON,
    EQUIP_KIND_WEAPON_2H: CRAFT_EQUIP_SLOT_GROUP_WEAPON,
    EQUIPMENT_SLOT_ARMOR_HEAD: CRAFT_EQUIP_SLOT_GROUP_HEAD,
    EQUIPMENT_SLOT_ARMOR_CHEST: CRAFT_EQUIP_SLOT_GROUP_CHEST,
    EQUIPMENT_SLOT_ARMOR_HANDS: CRAFT_EQUIP_SLOT_GROUP_HANDS,
    EQUIPMENT_SLOT_ARMOR_LEGS: CRAFT_EQUIP_SLOT_GROUP_LEGS,
    EQUIPMENT_SLOT_ARMOR_SHOES: CRAFT_EQUIP_SLOT_GROUP_SHOES,
    EQUIPMENT_SLOT_ACCESSORY_1: CRAFT_EQUIP_SLOT_GROUP_ACCESSORY,
    EQUIPMENT_SLOT_ACCESSORY_2: CRAFT_EQUIP_SLOT_GROUP_ACCESSORY,
    EQUIPMENT_SLOT_RING_1: CRAFT_EQUIP_SLOT_GROUP_ACCESSORY,
    EQUIPMENT_SLOT_RING_2: CRAFT_EQUIP_SLOT_GROUP_ACCESSORY,
    CATALOG_KIND_ACCESSORY: CRAFT_EQUIP_SLOT_GROUP_ACCESSORY,
    CATALOG_KIND_ACCESSORY_ANY: CRAFT_EQUIP_SLOT_GROUP_ACCESSORY,
    CATALOG_KIND_RING: CRAFT_EQUIP_SLOT_GROUP_ACCESSORY,
    CATALOG_KIND_RING_ANY: CRAFT_EQUIP_SLOT_GROUP_ACCESSORY,
    EQUIPMENT_SLOT_FABAO_1: CRAFT_EQUIP_SLOT_GROUP_FABAO,
    EQUIPMENT_SLOT_FABAO_2: CRAFT_EQUIP_SLOT_GROUP_FABAO,
    EQUIPMENT_SLOT_NATAL_FABAO: CRAFT_EQUIP_SLOT_GROUP_FABAO,
    EQUIPMENT_SLOT_FUBAO: CRAFT_EQUIP_SLOT_GROUP_FABAO,
    CATALOG_KIND_FABAO: CRAFT_EQUIP_SLOT_GROUP_FABAO,
    CATALOG_KIND_LINGBAO: CRAFT_EQUIP_SLOT_GROUP_FABAO,
    CATALOG_KIND_FABAO_ANY: CRAFT_EQUIP_SLOT_GROUP_FABAO,
}


def craft_equip_slot_group(slot: str) -> str | None:
    """Map an equipment.yaml slot/kind onto a workshop filter group.

    Args:
        slot: Catalog slot or pointer id from equipment.yaml.

    Returns:
        Group id such as ``weapon`` / ``head``, or ``None`` if not wearable gear.
    """
    key = str(slot or "").strip()
    if not key:
        return None
    if key in CRAFT_EQUIP_SLOT_TO_GROUP:
        return CRAFT_EQUIP_SLOT_TO_GROUP[key]
    return CRAFT_EQUIP_SLOT_TO_GROUP.get(canonical_equipment_slot(key))
