"""工坊品质、制作等级与配方筛选协议常量。"""

from __future__ import annotations

from typing import Final

from app.constants.equipment import (
    CATALOG_KIND_ACCESSORY,
    CATALOG_KIND_ACCESSORY_ANY,
    CATALOG_KIND_FABAO,
    CATALOG_KIND_FABAO_ANY,
    CATALOG_KIND_LINGBAO,
    CATALOG_KIND_RING,
    CATALOG_KIND_RING_ANY,
    CATALOG_KIND_WEAPON_1H,
    CATALOG_KIND_WEAPON_ANY,
    EQUIP_KIND_WEAPON_2H,
    EQUIPMENT_SLOT_ACCESSORY_1,
    EQUIPMENT_SLOT_ACCESSORY_2,
    EQUIPMENT_SLOT_ARMOR_CHEST,
    EQUIPMENT_SLOT_ARMOR_HANDS,
    EQUIPMENT_SLOT_ARMOR_HEAD,
    EQUIPMENT_SLOT_ARMOR_LEGS,
    EQUIPMENT_SLOT_ARMOR_SHOES,
    EQUIPMENT_SLOT_FABAO_1,
    EQUIPMENT_SLOT_FABAO_2,
    EQUIPMENT_SLOT_FUBAO,
    EQUIPMENT_SLOT_NATAL_FABAO,
    EQUIPMENT_SLOT_RING_1,
    EQUIPMENT_SLOT_RING_2,
    EQUIPMENT_SLOT_WEAPON_1,
    EQUIPMENT_SLOT_WEAPON_2,
    canonical_equipment_slot,
)

# 造物品阶（与 §0.0.3 物品稀有度同键：粗糙～太古）
CRAFT_QUALITY_GRAY: Final[str] = "gray"  # 粗糙
CRAFT_QUALITY_WHITE: Final[str] = "white"  # 普通
CRAFT_QUALITY_GREEN: Final[str] = "green"  # 优秀
CRAFT_QUALITY_BLUE: Final[str] = "blue"  # 精良
CRAFT_QUALITY_PURPLE: Final[str] = "purple"  # 史诗
CRAFT_QUALITY_ORANGE: Final[str] = "orange"  # 传说
CRAFT_QUALITY_RED: Final[str] = "red"  # 太古

CRAFT_QUALITY_DEFAULT: Final[str] = CRAFT_QUALITY_WHITE

CRAFT_QUALITIES: Final[tuple[str, ...]] = (
    CRAFT_QUALITY_GRAY,
    CRAFT_QUALITY_WHITE,
    CRAFT_QUALITY_GREEN,
    CRAFT_QUALITY_BLUE,
    CRAFT_QUALITY_PURPLE,
    CRAFT_QUALITY_ORANGE,
    CRAFT_QUALITY_RED,
)

CRAFT_QUALITY_LABEL_ZH: Final[dict[str, str]] = {
    CRAFT_QUALITY_GRAY: "粗糙",
    CRAFT_QUALITY_WHITE: "普通",
    CRAFT_QUALITY_GREEN: "优秀",
    CRAFT_QUALITY_BLUE: "精良",
    CRAFT_QUALITY_PURPLE: "史诗",
    CRAFT_QUALITY_ORANGE: "传说",
    CRAFT_QUALITY_RED: "太古",
}

# 旧四档（凡品/良品/上品/极品）→ 七档；读存量 meta / 旧 YAML 权重时归一
LEGACY_CRAFT_QUALITY_MAP: Final[dict[str, str]] = {
    "common": CRAFT_QUALITY_WHITE,
    "fine": CRAFT_QUALITY_GREEN,
    "rare": CRAFT_QUALITY_BLUE,
    "superb": CRAFT_QUALITY_PURPLE,
    "凡品": CRAFT_QUALITY_WHITE,
    "良品": CRAFT_QUALITY_GREEN,
    "上品": CRAFT_QUALITY_BLUE,
    "极品": CRAFT_QUALITY_PURPLE,
}

# 兼容旧常量名（请改用七档 id）
CRAFT_QUALITY_COMMON: Final[str] = CRAFT_QUALITY_WHITE
CRAFT_QUALITY_FINE: Final[str] = CRAFT_QUALITY_GREEN
CRAFT_QUALITY_RARE: Final[str] = CRAFT_QUALITY_BLUE
CRAFT_QUALITY_SUPERB: Final[str] = CRAFT_QUALITY_PURPLE

# 制作等级不足（开工拒绝）
ERR_CRAFT_LEVEL: Final[int] = 40086
ERR_CRAFT_LEVEL_ZH: Final[str] = "制作等级不足，无法学习或制造该图纸"

# 阵法等非制造业配方不可开工
ERR_CRAFT_NOT_WORKSHOP: Final[int] = 40087
ERR_CRAFT_NOT_WORKSHOP_ZH: Final[str] = "阵法不属于工坊制造业"

# 炼器配方栏「部位」筛选（玩法分组，不是 17 区指针槽本身）
CRAFT_EQUIP_SLOT_GROUP_WEAPON: Final[str] = "weapon"  # 武器
CRAFT_EQUIP_SLOT_GROUP_HEAD: Final[str] = "head"  # 头部
CRAFT_EQUIP_SLOT_GROUP_CHEST: Final[str] = "chest"  # 胸甲
CRAFT_EQUIP_SLOT_GROUP_HANDS: Final[str] = "hands"  # 护手
CRAFT_EQUIP_SLOT_GROUP_LEGS: Final[str] = "legs"  # 腿甲
CRAFT_EQUIP_SLOT_GROUP_SHOES: Final[str] = "shoes"  # 鞋履
CRAFT_EQUIP_SLOT_GROUP_ACCESSORY: Final[str] = "accessory"  # 饰品
CRAFT_EQUIP_SLOT_GROUP_FABAO: Final[str] = "fabao"  # 法宝

CRAFT_EQUIP_SLOT_GROUPS: Final[tuple[str, ...]] = (
    CRAFT_EQUIP_SLOT_GROUP_WEAPON,
    CRAFT_EQUIP_SLOT_GROUP_HEAD,
    CRAFT_EQUIP_SLOT_GROUP_CHEST,
    CRAFT_EQUIP_SLOT_GROUP_HANDS,
    CRAFT_EQUIP_SLOT_GROUP_LEGS,
    CRAFT_EQUIP_SLOT_GROUP_SHOES,
    CRAFT_EQUIP_SLOT_GROUP_ACCESSORY,
    CRAFT_EQUIP_SLOT_GROUP_FABAO,
)

CRAFT_EQUIP_SLOT_GROUP_LABELS_ZH: Final[dict[str, str]] = {
    CRAFT_EQUIP_SLOT_GROUP_WEAPON: "武器",
    CRAFT_EQUIP_SLOT_GROUP_HEAD: "头部",
    CRAFT_EQUIP_SLOT_GROUP_CHEST: "胸甲",
    CRAFT_EQUIP_SLOT_GROUP_HANDS: "护手",
    CRAFT_EQUIP_SLOT_GROUP_LEGS: "腿甲",
    CRAFT_EQUIP_SLOT_GROUP_SHOES: "鞋履",
    CRAFT_EQUIP_SLOT_GROUP_ACCESSORY: "饰品",
    CRAFT_EQUIP_SLOT_GROUP_FABAO: "法宝",
}

# equipment.yaml slot / equip_kind → 工坊部位组
CRAFT_EQUIP_SLOT_TO_GROUP: Final[dict[str, str]] = {
    EQUIPMENT_SLOT_WEAPON_1: CRAFT_EQUIP_SLOT_GROUP_WEAPON,
    EQUIPMENT_SLOT_WEAPON_2: CRAFT_EQUIP_SLOT_GROUP_WEAPON,
    CATALOG_KIND_WEAPON_1H: CRAFT_EQUIP_SLOT_GROUP_WEAPON,
    CATALOG_KIND_WEAPON_ANY: CRAFT_EQUIP_SLOT_GROUP_WEAPON,
    EQUIP_KIND_WEAPON_2H: CRAFT_EQUIP_SLOT_GROUP_WEAPON,
    EQUIPMENT_SLOT_ARMOR_HEAD: CRAFT_EQUIP_SLOT_GROUP_HEAD,
    EQUIPMENT_SLOT_ARMOR_CHEST: CRAFT_EQUIP_SLOT_GROUP_CHEST,
    EQUIPMENT_SLOT_ARMOR_HANDS: CRAFT_EQUIP_SLOT_GROUP_HANDS,
    EQUIPMENT_SLOT_ARMOR_LEGS: CRAFT_EQUIP_SLOT_GROUP_LEGS,
    EQUIPMENT_SLOT_ARMOR_SHOES: CRAFT_EQUIP_SLOT_GROUP_SHOES,
    EQUIPMENT_SLOT_ACCESSORY_1: CRAFT_EQUIP_SLOT_GROUP_ACCESSORY,
    EQUIPMENT_SLOT_ACCESSORY_2: CRAFT_EQUIP_SLOT_GROUP_ACCESSORY,
    EQUIPMENT_SLOT_RING_1: CRAFT_EQUIP_SLOT_GROUP_ACCESSORY,
    EQUIPMENT_SLOT_RING_2: CRAFT_EQUIP_SLOT_GROUP_ACCESSORY,
    CATALOG_KIND_ACCESSORY: CRAFT_EQUIP_SLOT_GROUP_ACCESSORY,
    CATALOG_KIND_ACCESSORY_ANY: CRAFT_EQUIP_SLOT_GROUP_ACCESSORY,
    CATALOG_KIND_RING: CRAFT_EQUIP_SLOT_GROUP_ACCESSORY,
    CATALOG_KIND_RING_ANY: CRAFT_EQUIP_SLOT_GROUP_ACCESSORY,
    EQUIPMENT_SLOT_FABAO_1: CRAFT_EQUIP_SLOT_GROUP_FABAO,
    EQUIPMENT_SLOT_FABAO_2: CRAFT_EQUIP_SLOT_GROUP_FABAO,
    EQUIPMENT_SLOT_NATAL_FABAO: CRAFT_EQUIP_SLOT_GROUP_FABAO,
    EQUIPMENT_SLOT_FUBAO: CRAFT_EQUIP_SLOT_GROUP_FABAO,
    CATALOG_KIND_FABAO: CRAFT_EQUIP_SLOT_GROUP_FABAO,
    CATALOG_KIND_LINGBAO: CRAFT_EQUIP_SLOT_GROUP_FABAO,
    CATALOG_KIND_FABAO_ANY: CRAFT_EQUIP_SLOT_GROUP_FABAO,
}


def craft_equip_slot_group(slot: str) -> str | None:
    """Map an equipment.yaml slot/kind onto a workshop filter group.

    Args:
        slot: Catalog slot or pointer id from equipment.yaml.

    Returns:
        Group id such as ``weapon`` / ``head``, or ``None`` if not wearable gear.
    """
    key = str(slot or "").strip()
    if not key:
        return None
    if key in CRAFT_EQUIP_SLOT_TO_GROUP:
        return CRAFT_EQUIP_SLOT_TO_GROUP[key]
    return CRAFT_EQUIP_SLOT_TO_GROUP.get(canonical_equipment_slot(key))
